### ISSUE TITLE
Refactor / Document IDCT and Scaling

### ISSUE THREAD

**Issue by pleonex** [pleonex/PlayMobic#6]
## Context

The `ResidualEncoding` class decodes and adds the residual with the predicted colors in the inter frame.

The implementation is based on an inverse DCT transform  (`DiscreteCosineTransformer`) and quantization / scaling (`Quantization`). These two classes started from the H.264 and JPEG specs but, they had to be fixed several times to make it work in this codec.

These are key parts of the codec. It's required to have a solid implementation and understand before starting the encoding implementation.

## Feature description

It would be great to spend some time understanding the actual algorithm behind. Then refactor, add tests and document their specification.

### References

A nice resource to understand these kinds of implementation: https://github.com/GlaireDaggers/Pretty-Fast-Video/blob/main/src/dct.rs

## Task list

- [ ] Create unit tests for IDCT
- [ ] Learn and refactor code for IDCT
- [ ] Create unit tests for quantization
- [ ] Learn and refactor code for quantization
- [ ] Document specification of IDCT and quantization
